#docker-compose -f .\minio.yml up --build -d
version: '3.8'

services:
  #minio
  minio:
    image: minio/minio:RELEASE.2022-06-07T00-33-41Z
    container_name: minio
    hostname: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio1234
    volumes:
      - ./data/minio_data:/data
    ports:
      - "8000:8000"
      - "8001:8001" # tap localhost:9001 to access to minio
    networks:
      - app-network

networks:
  app-network:
    external: true